Eoc free response
openstax/kitchen pull request #198
Opened 2021-04-28 21:42 UTC by LostMojo

Moves free response questions to the end of the chapter & creates a container for them

2021-05-03 14:20 UTC, LostMojo commented
The legacy baked free response is a composite page container containing a title, metadata and exercises (that are baked by another process) and it looks like this:

![Screen Shot 2021-05-03 at 9 14 50 AM](https://user-images.githubusercontent.com/5740972/116888187-c5904800-abf0-11eb-8c25-391ff7b0dbac.png)

2021-05-04 16:32 UTC, jpslav requested changes

2021-05-04 16:32 UTC, jpslav commented on lib/kitchen/directions/bake_free_response/v1.rb
> +      end
A clipboard is essentially an array, so I'm wondering if we don't need both an array and a clipboard on lines 10 and 11.

```ruby
def bake(chapter:, metadata_source:, append_to:)
  @metadata_elements = metadata_source.children_to_keep.copy

  @free_response_clipboard = Kitchen::Clipboard.new
  chapter.non_introduction_pages.each do |page|
    free_response_questions = page.free_response
    next if free_response_questions.none?

    free_response_questions.search('h3').trash
    title = Kitchen::Directions::EocSectionTitleLinkSnippet.v1(page: page)
    free_response_questions.each do |free_response_question|
      free_response_question.prepend(child: title)
      free_response_question&.cut(to: @free_response_clipboard)
    end
  end

  append_to_element = append_to || chapter
  @title_tag = append_to ? 'h3' : 'h2'

  append_to_element.append(child: render(file: 'free_response.xhtml.erb'))
end
```

and then do `@free_response_clipboard.paste` in the `.xhtml.erb` file?

2021-05-04 16:32 UTC, jpslav commented on lib/kitchen/directions/bake_free_response/v1.rb
> +          free_response_question&.cut(to: free_response_clipboard)
Guessing you don't need the `&` here since it isn't used on line 19

2021-05-04 20:14 UTC, jpslav approved these changes

2021-05-04 20:23 UTC, merged