BakeFirstElements: moved selectors from recipe to kitchen
openstax/kitchen pull request #233
Opened 2021-05-24 01:46 UTC by KarinaMendez2

2021-05-24 15:57 UTC, jpslav requested changes
Some test coverage is needed too.

2021-05-24 15:57 UTC, jpslav commented on lib/kitchen/directions/bake_first_elements.rb
> +          '.os-problem-container > .os-table',
please add the tag names here as you can per https://openstax.slack.com/archives/C022NETP39N/p1621863752137000

2021-05-25 15:19 UTC, kswanson33 requested changes

2021-05-25 15:19 UTC, kswanson33 commented on spec/directions/bake_first_elements_spec.rb
> +                      <span class="first-element" data-type="media">Media</div>
and this one

2021-05-25 15:22 UTC, kswanson33 approved these changes
❤️

2021-05-25 15:27 UTC, jpslav approved these changes

2021-05-25 15:28 UTC, merged