Making a default strategy for eob exercises
openstax/kitchen pull request #253
Opened 2021-06-03 22:41 UTC by KarinaMendez2

2021-06-04 15:35 UTC, kswanson33 approved these changes

2021-06-04 15:37 UTC, kswanson33 requested changes
oh wait i just saw that codecov is complaining nvm

2021-06-04 15:37 UTC, kswanson33 commented on lib/kitchen/directions/move_solutions_to_answer_key/v1.rb
>            Strategies::AmericanGovernment
this may be why codecov is complaining ... does this strategy exist anymore? if not, this case is not needed

2021-06-04 18:45 UTC, brittany-johnson approved these changes

2021-06-07 14:46 UTC, ajluk approved these changes

2021-06-07 16:15 UTC, kswanson33 approved these changes

2021-06-07 16:18 UTC, merged