Optimize selectors
openstax/kitchen pull request #281
Opened 2021-06-17 22:50 UTC by KarinaMendez2

2021-06-17 22:58 UTC, jpslav requested changes

2021-06-17 22:58 UTC, jpslav commented on lib/kitchen/directions/move_solutions_to_answer_key/strategies/default.rb
> +          chapter.search("#{klass} div[data-type='solution']").each do |solution|
if now passing in `div.some_class` then need to change `@classes` to `@selectors` and `klass` to `selector` b/c these aren't just classes any more.

2021-06-21 16:49 UTC, jpslav approved these changes

2021-06-21 17:13 UTC, brittany-johnson approved these changes

2021-06-21 17:34 UTC, merged