Indexes of different types
openstax/kitchen pull request #300
Opened 2021-07-05 13:57 UTC by wilkus27

In Polish Psychology there are three types of indexes: with names, regular one, and with foreign terms.

2021-08-09 15:29 UTC, wilkus27 commented
@kswanson33 PR https://github.com/openstax/kitchen/pull/301 was based on this one. I merged it here. Could you review also this  PR? It has a few small additional changes and it's updated with the newest code from main. Sorry for the confusion :slightly_smiling_face:

2021-08-12 16:27 UTC, kswanson33 requested changes
Small change request, but everything else is looking good!

2021-08-13 15:16 UTC, wilkus27 commented
@kswanson33 I added requested changes and I made small fix for index section name. PR is ready for re review :wink:

2021-08-16 18:20 UTC, kswanson33 approved these changes

2021-08-18 07:40 UTC, merged