create bake habnbook module
openstax/kitchen pull request #316
Opened 2021-07-20 16:42 UTC by ajluk

Issue:  #315

2021-07-22 15:59 UTC, ajluk commented on lib/kitchen/directions/bake_handbook/v1.rb
> +    def fix_nested_section_headers(page:)
I have rewritten this method using case statement to make the headers fir the the section depth (nesting) in the content. I left commented  how it was done previously to make the goal more clear. If someone will have a better idea how to code it, please fell free to comment! :slightly_smiling_face:

2021-07-23 20:27 UTC, kswanson33 requested changes
This implementation contains a lot of similar searches over the content. Knowing that searching is one of the more time-intensive parts of baking, would it be possible to memoize any of the `page($.handbook).search('> section')` calls?

Otherwise, this is looking good!

2021-07-23 20:27 UTC, kswanson33 commented on lib/kitchen/directions/bake_handbook/v1.rb
> +            <span class="os-text">#{first_section_title_text}</span>
is this variable needed? or could `first_section_title.text` be used here?

2021-07-23 20:27 UTC, kswanson33 commented on lib/kitchen/directions/bake_handbook/v1.rb
> +        section_data_depth = section.raw['data-depth']
i believe `section.raw['data-depth']` is equivalent to `section[:'data-depth']` -- might be syntactically nicer! 🙂

2021-07-28 14:53 UTC, ajluk commented
@kswanson33 I omitted the problem with using clipboard on objectives strings in ` bake_handbook_objectives` method we were discuss on slack by pushing them to an array and use it in the same iteration by include it in ` bake_first_section_title_and_objectives` method . It is a little different approach. Let me know what do you think about it :slightly_smiling_face:

2021-07-28 19:08 UTC, kswanson33 commented on lib/kitchen/directions/bake_handbook/v1.rb
> +        )
this can just be `page.title.append(sibling: outline_html)` -- no need for string interpolation!

2021-07-28 19:08 UTC, kswanson33 approved these changes
approving, but I did make one minor comment!

2021-07-29 11:42 UTC, merged